#!/usr/bin/env cmake -P
cmake_minimum_required(VERSION 3.0.2)

include(${CMAKE_CURRENT_LIST_DIR}/../_execute.cmake)
execute_cmake()
# execute(make)
# execute(make my_target0)
# execute(make my_target1)
# execute(make my_target2)
# execute(make my_target3)
# execute(make my_target4)
# execute(make my_target5)
# execute(make my_target6)
# execute(make my_target7)
# execute(make my_target8)
# execute(make my_target9_1 my_target9_2)
execute(make my_target10)
