require 'fileutils'

directory 'gen'

task :default => 'gen' do |t|
  Dir.chdir(t.prerequisites.first) do
    sh 'cmake ..'
    sh 'make'
    sh 'make test ARGS="-V --output-on-failure"'
  end
end

task :clean do
  FileUtils.rm_rf 'gen'
end
